MY_SPRITE=/assets/userC.png
PARTNER_SPRITE=/assets/userD.png
MY_OFFLINE_SHEET=/assets/me_offline.png
MY_SLEEP_SHEET=/assets/me_sleep.png
PARTNER_OFFLINE_SHEET=/assets/her_offline.png
PARTNER_SLEEP_SHEET=/assets/her_sleep.png
MY_REACTION_SHEET=/assets/me_reaction.png
MY_SEND_SHEET=/assets/me_send.png
PARTNER_REACTION_SHEET=/assets/her_reaction.png
PARTNER_SEND_SHEET=/assets/her_send.png

MY_OFFLINE_FRAME_W=270
MY_OFFLINE_FRAME_H=335
MY_SLEEP_FRAME_W=192
MY_SLEEP_FRAME_H=268
MY_REACTION_FRAME_W=244
MY_REACTION_FRAME_H=372
MY_SEND_FRAME_W=223
MY_SEND_FRAME_H=380

PARTNER_OFFLINE_FRAME_W=287
PARTNER_OFFLINE_FRAME_H=340
PARTNER_SLEEP_FRAME_W=198
PARTNER_SLEEP_FRAME_H=239
PARTNER_REACTION_FRAME_W=244
PARTNER_REACTION_FRAME_H=402
PARTNER_SEND_FRAME_W=237
PARTNER_SEND_FRAME_H=400
